permalink: /:year:month:day/:title
url: https://shoshosh.github.io
baseurl: /shoshosh

# variables
name: WeBLog
description: 공부하는 W e B L o g
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
    
disqus-shortname: shoshosh